### ISSUE TITLE
Problems with clAmdFft library

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#157]
```
The recent changes in ADDA made it produce results in combination with clAmdFft 
1.8.239 for many cases. However, this library is not yet as robust as we want 
it to be. So this issue is supposed to discuss the existing shortcomings:

1) The library can be tested on any computer using client application, supplied 
with it. However, it only works in single precision, which is currently 
irrelevant to ADDA. Still, this tests produce failures on Nvidia GeForce 540M 
(on Windows 7 64-bit) - see comment to r1155. However, these tests are based on 
transforming the constant array and testing the results against the expected 
output (zeros almost everywhere). So the failure can be caused by loss of 
precision. Probably because of that ADDA works fine on the same machine - see 
r1178 (produces sufficiently accurate results).

2) On the same machine as above, when ADDA is compiled in 32-bit mode and 
linked to 32-bit clAmdFft it crashes for almost any grid sizes (-grid ...), 
except 6, 10, 14, and 16. The corresponding (working) FFT sizes are 12, 20, 30, 
and 32. I localized the crash to creation of the first FFT plan, and the 
critical part is double precision. So crash occurs even for a single (not 
batched) FFT of a double precision array, but works fine for any batch of 
single-precision ones.

The crash is most probably a library issue, but it might be also connected to 
the OpenCL.dll (32-bit) provided by Nvidia (I used driver 306.97). 
```

r1155 - bf6ae1858f60edc96ce6b8ceb0ed43f61559f751
r1178 - 746455d2c85d6498475dab43c67b7e8f8ea2b6a0

Original issue reported on code.google.com by `yurkin` on 20 Jan 2013 at 5:29
- Blocked on: #204

**Comment by myurkin** [comment]
This issue need to be reconsidered in line with changes by #204.

**Comment by myurkin** [comment]
I've tested clFFT client 2.12.2 on Windows 10 with Nvidia drivers 457.30 with sizes from 1 to 32 omitting prime numbers >= 17.

- Single precision `clFFT-client.exe -x $size` fails for 11, 13, and their multiples (22, 26)
- Double precision `clFFT-client.exe --double -x $size` fails for 7, 11, 13, and their multiples (14, 21, 22, 26, 28)

Then I tested the same on Intel HD Graphics 630 (driver version 27.20.100.8477), adding `--platform 1` to the command line. For both single and double precision it failed for sizes 7, 11, 13, and their multiples.

However, then I ran seq and ocl version of ADDA with -grid 7, 11, and 13 (FFT sizes are then twice of that) on both above-mentioned GPUs the result for Cext is identical withing all shown digits. The same tests are included in automatic test suites (`tests/2exec`) since afcfc94 and also pass.

Therefore, it seems that the current loss of precision in clFFT library is negligible.
