### ISSUE TITLE
Nearfield calculation when there are multiple domains.

### ISSUE THREAD

**Issue by limjoowon** [adda-team/adda#241]
Hello,

I have two questions.

1. I have been using the program to generate nearfields. It goes well when there is only one domain.
However, when there are multiple domains(Ex. Nmat=2), gendip.f generates an error. The error occurs at the following part of gendip.f

!---------------------get number of dipoles-------------------------
         OS=0
         open(UNIT=3114,FILE='target',STATUS='OLD',ERR=900)
         read(3114,*) 
         read(3114,*)      
         read(3114,*)
 399     read(3114,*,ERR=400,END=200) xi,yj,zk
         goto 401
 400          write(*,*) 'NMAT>1'
         goto 399
 401          OS=OS+1
         goto 399
 200     write(*,*) 'Readed Dipoles',OS
         close(3114)

I think this is because 'target' file of multiple domain case has a different format as followings,

A. An example target file (single domain)
#generated by ADDA v.1.3b6
#shape: 'sphere'
#box size: 20x20x20
0 0 0
...

B. An example target file (Multiple domain)
#generated by ADDA v.1.3b6
#shape: 'read'
#box size: 20x20x20
Nmat=2
0 0 0 1
...

I am wondering whether 'Nmat=2' and the domain number (which is the last column in target file of multiple domains) are used to calculate the nearfield. 
If it is not required to have them to calculate the nearfield, I can regenerate target file to get rid of the line (Nmat=2) and the last column and I think it will work as well as the single domain case.

2. To calculate nearfield, it requires 'target' and 'DipPol-Y' generated by comment 'save_geom' and 'store_dip_pol'. I use these two to calculate nearfield. I am wondering whether it is okay to run the program with '-sym enf' comment to make it fast without affecting the result.

Could you give me comments?

Best,

Joowon

**Comment by myurkin** [comment]
(1). Indeed, the `near_field` works only for single-domain particles, but it really should not care. So if you provide him a single-domain format of the shape file, it should work fine. There are several options here:

* update `gendip.f` to properly process multi-domain files. Should be easy, but I am reluctant to do it, since I have very little experience with Fortran and `misc` packages are kind of side-work. Still, if someone provides a patch, that would be great.
* make ADDA produce such files. Unfortunately, `-sg_format text` won't help right now, so there is a separate #242 for that.
* convert the shape file to a different format manually or by a script. This one-liner in the pipe should do the trick (prints only first three fields on lines starting with number or minus, skips Nmat and copies all other line):
  ```awk
  awk '/^[0-9-]/{print $1 " " $2 " " $3; next} !/^Nmat=/'
  ```
  But since `gendip` expects the shape file in `target`, you should convert the shape file produced by ADDA (e.g. `shape.geom`) as
  ```bash
  awk '/^[0-9-]/{print $1 " " $2 " " $3; next} !/^Nmat=/' shape.geom > target
  ```
  It can even be run under Windows, using MSYS shell.

Joowon, can you please test the last option (with `awk`)?

**Comment by myurkin** [comment]
(2). General advice about `-sym_enf`: if you hesitate, do not use it. But in your specific case it can be used, if you need the near field only for **one** incident polarization. And don't forget to discard ADDA output that depends on both polarizaitons, e.g. `mueller`.

**Comment by limjoowon** [comment]
Thank you for your reply.

(1) At this moment, I don't have an access to a computer source but I would like to try next week once I have the access again.

(2) So, in a nutshell, it is not recommneded in general, but I guess that it would not make any difference in case of nearfield calculation for y polarized light.

Best,

Joowon.

**Comment by myurkin** [comment]
(2) Yes, you can use it to save time for this specific problem. Just be careful.

**Comment by limjoowon** [comment]
As suggested above by myurkin,

"awk '/^[0-9-]/{print $1 " " $2 " " $3; next} !/^Nmat=/' shape.geom > target" works.

Joowon
