### ISSUE TITLE
building with opencl fails

### ISSUE THREAD

**Issue by mgawan** [adda-team/adda#272]
I am trying to build adda with OpenCL to use GPUs. However, the build fails at linking stage with the below error:

```
echo -n "gcc -L/global/homes/m/mgawan/lib -w -lm -lfftw3 -lclFFT -L/usr/common/software/cuda/10.2.89/lib64/libOpenCL.so  -lg2c" > .ldopts
Building adda_ocl
gcc -o adda_ocl ADDAmain.o CalculateE.o calculator.o chebyshev.o cmplx.o comm.o crosssec.o GenerateB.o interaction.o io.o iterative.o linalg.o make_particle.o memory.o mt19937ar.o param.o Romberg.o sinint.o somnec.o timing.o vars.o fft.o oclcore.o oclmatvec.o d07hre.o d09hre.o d113re.o d132re.o dadhre.o dchhre.o dcuhre.o dfshre.o dinhre.o drlhre.o dtrhre.o propaesplibreintadda.o   -L/global/homes/m/mgawan/lib -w -lm -lfftw3 -lclFFT -L/usr/common/software/cuda/10.2.89/lib64/libOpenCL.so  -lg2c
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lg2c
```

If I try building it with OPTIONS="NO_FORTRAN", it fails with this error:
```
Building adda_ocl
gcc -o adda_ocl ADDAmain.o CalculateE.o calculator.o chebyshev.o cmplx.o comm.o crosssec.o GenerateB.o interaction.o io.o iterative.o linalg.o make_particle.o memory.o mt19937ar.o param.o Romberg.o sinint.o somnec.o timing.o vars.o fft.o oclcore.o oclmatvec.o    -L/global/homes/m/mgawan/lib -w -lm -lfftw3 -lclFFT -L/usr/common/software/cuda/10.2.89/lib64/libOpenCL.so
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: oclcore.o: undefined reference to symbol 'clReleaseContext@@OPENCL_1.0'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/common/software/cuda/10.2.89/lib64/libOpenCL.so.1: error adding symbols: DSO missing from command line
```

I am using opencl libraries included with CUDA 10.2, could that be the issue? If so, what could be a work around?

**Comment by myurkin** [comment]
The first error, indeed, seems to be related to Fortran compilation. The Makefile couldn't find `gfortran`, but finds `g77` and not `g2c.lib`, which is strange. Anyway, this can be fixed by properly installing `gfortran`. However, `OPTIONS="NO_FORTRAN"` is a valid workaround as well.

Concerning the second error, I have not compiled OpenCL on Unix for a long time. However, the instructions at https://github.com/adda-team/adda/wiki/OpenCL suggest that CUDA OpenCL libraries may indeed cause issues. These instructions contain two other options to supply libraries and headers - please try them. And please comment here afterwards, which option works (if any).

**Comment by mgawan** [comment]
Since I am trying to build this on NERSC's system, installing ubuntu packages would be tricky. The third option of getting the headers from the repository sounds feasible. But do you think including different headers will solve the problem? From the above errors, I thought the issue was with the library file **libOpenCL.so**.

Also, I built clFFT (pre built binaries were not compatible) using the same CUDA provided openCL headers and library files and it went well.

**Comment by myurkin** [comment]
Indeed the problem is with library libOpenCL.so. Seems that ADDA calls some functions that are not present there. It can even be some weird incompatibility between headers and library. Overall, the problem is that CUDA is not very fond of OpenCL and hence the support may be not full. 

So the idea of all workarounds is to get some other libOpenCL.so for linking. Either through some package system (or modules, whatever is used for your system), or linking to the runtime library (provided by driver - I do not remember how exactly it is called) instead of library definition for linking (provided by CUDA).  The latter will require modification of environment as described in the wiki page. But even replacing only the header files may potentially solve the issue.

The fact that clFFT builds OK suggests that only some of the OpenCL calls are not operational, so that potentially ADDA can be modified to avoid this issue (but I do not know how easy it is).

**Comment by myurkin** [comment]
@mgawan - do you have any update on this issue?

**Comment by mgawan** [comment]
thanks for checking, we tried by replacing headers and a few other minor things but the same error persisted, we ended up using the MPI version in the interest of time. MPI version worked fine.

**Comment by myurkin** [comment]
I have been building ocl version on my cluster and noticed that clFFT had troubles linking to libOpenCL.so with similar error message, as you reported. I managed to fix it by uncommenting the line
```
LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs
```
in `ocl\Makefile`. There are also comments around it explaining the issue.

Alternatively, I could build without any changes by avoiding using clFFT, invoking
```
make ocl OPTIONS=CLFFT_APPLE
```
However, that options requires the latest ADDA sources, due to the recently fixed bug (#276). And you can combine it with `NO_FORTRAN` by `OPTIONS="NO_FORTRAN CLFFT_APPLE"`.

@mgawan, can you please check if any of these two ideas help in your case? Do not forget to invoke `make cleanocl` before a new compilation.

**Comment by mgawan** [comment]
thanks for doing this, I will try to give it a go next month.

**Comment by mgawan** [comment]
Hi tried building again with the options you mentioned, this time it failed with this error:
```
Linking needs to be redone
echo -n "gcc -L/usr/common/software/sles15_cgpu/fftw/3.3.8/intel/lib -w -lm -lfftw3 -lOpenCL -lstdc++" > .ldopts
Building adda_ocl
gcc -o adda_ocl ADDAmain.o CalculateE.o calculator.o chebyshev.o cmplx.o comm.o crosssec.o GenerateB.o interaction.o io.o iterative.o linalg.o make_particle.o memory.o mt19937ar.o param.o Romberg.o sinint.o somnec.o timing.o vars.o fft.o oclcore.o oclmatvec.o   fft_execute.o fft_setup.o fft_kernelstring.o -L/usr/common/software/sles15_cgpu/fftw/3.3.8/intel/lib -w -lm -lfftw3 -lOpenCL -lstdc++
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: skipping incompatible /usr/lib/libOpenCL.so when searching for -lOpenCL
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
make[1]: *** [../common.mk:73: adda_ocl] Error 1
```

this is the command I am using to build : 
`make ocl OPTIONS="NO_FORTRAN CLFFT_APPLE" FFTW3_INC_PATH=/usr/common/software/sles15_cgpu/fftw/3.3.8/intel/include FFTW3_LIB_PATH=/usr/common/software/sles15_cgpu/fftw/3.3.8/intel/lib`

I cloned a fresh copy of the repo to try the above. It looks like its having issue with OpenCL libs, is it possible to direct it towards the CUDA OpenCL libs, would that work?

**Comment by mgawan** [comment]
nevermind, I was able to hardcode the paths in Makefile to make it work. Its building and working fine on our system now. Thanks for you help!

**Comment by myurkin** [comment]
@mgawan , thanks for the update. I am glad that it finally works. I have only a small remark - the Apple FFT routines that you use are far from optimal. So if, for instance, you plan to test the performance of adda_ocl, it is highly recommended to switch to clFFT. Installing it should be easy - I have recently updated the [instructions for that](https://github.com/adda-team/adda/wiki/InstallingclFFT).
