### ISSUE TITLE
residual norm haven't decrease

### ISSUE THREAD

**Issue by lxfsd** [adda-team/adda#328]
My problem is 'Residual norm haven't decreased for maximum allowed number of iterations'
Is this problem caused by my graphics card running out of memory?Or is there some other reasons？

**Comment by myurkin** [comment]
This is definitely not a memory issue, since the required memory is independent of the number of orientations. In general, there are two potential reasons (see Section 12.1 "Iterative solver" of the [manual](https://github.com/adda-team/adda/blob/master/doc/manual.pdf)):
- unexpected breakdown for specific problem parameters - that is easy to fix by, e.g., changing the size by 0.01% or choosing another iterative solver.
- the combination of particle size and refractive index is overall challenging for the DDA. There are some options to try (different iterative solver, `init_field wkb`, and reduced ε_iter, e.g., `-eps 3`), but they only extend the applicability domain to some extent.

I may try to provide more specific advice if you give more details of your simulations.

**Comment by lxfsd** [comment]
ok,i see.thanks I'll try to use these methods you provided and then give feedback here

**Comment by lxfsd** [comment]
I found a new problem that was that I would get an error when compiling mpi'.It appears in the dialog box‘*** No rule to make target '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdbool.h', needed by 'ADDAmain.o'.  Stop.’
Do you know how to solution this problem

**Comment by myurkin** [comment]
Again, you provide very little information. I advice to run `make clean` and then `make mpi`. If the problem persists, please make a new issue here and provide there all relevant information, according to the issue template.

**Comment by lxfsd** [comment]
ok,thanks.I've fixed this issue
